### ISSUE TITLE
Map not rendering locations

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#75]
The map (https://encyclopedia.densho.org/map/#) is no longer displaying locations. The section of the template that should be rendering the location data that is consumed by the front-end javascript is not functioning (https://github.com/densho/encyc-front/blob/master/front/locations/templates/locations/locations.html#L216).

**Comment by GeoffFroh** [comment]
bad data in `densho-vocab:/api/0.2/facilities.xml`

**Comment by gjost** [comment]
Problem was some bad data in `densho-vocab`.  This caused `encyc-psms` to crash when trying to display data in the API.  Partial fix in `encyc-psms` commit `10efcd7` for package `encycpsms-master~1.1.5`.

The other part of the fix will be to mod `encyc-front` `front/locations/templates/locations/locations.html` so that missing data is noted in comments in the HTML.  This way the page will still mostly work even with missing data.
